# get data from remote relay node
# [source]
# type = "N2N"
# address = "relays-new.cardano-mainnet.iohk.io:3001"

# get data from local node?? 
[source]
type = "N2C"
path = "data/cardano-node-mainnet/node.socket"

[[reducers]]
type = "UtxoByAddress"
# key_prefix = "c1"
filter = ["stake1uy6f5wg695g33ck8emlyx97vyfxyw8pmvgu5aq6hxgxscgg9s58ah"]

[[reducers]]
type = "PointByTx"
key_prefix = "c2"

[[reducers]]
type = "PoolByStake"
key_prefix = "c3"

[storage]
type = "Redis"
connection_params = "redis://127.0.0.1:6379"

[intersect]
type = "Point"
value = [39916796, "e72579ff89dc9ed325b723a33624b596c08141c7bd573ecfff56a1f7229e4d09"] # last mary block

[chain]
type = "Mainnet"

[policy]
missing_data = "Skip"
