[source]
type = "N2N"
address = "preprod-node.world.dev.cardano.org:30000"

# enable the "UTXO by Address" collection
[[reducers]]
type = "UtxoByAddress"
# you can optionally prefix the keys in the collection
key_prefix = "c1"
# you can optionally only process UTXO from a set of predetermined addresses
filter = ["addr1qy8jecz3nal788f8t2zy6vj2l9ply3trpnkn2xuvv5rgu4m7y853av2nt8wc33agu3kuakvg0kaee0tfqhgelh2eeyyqgxmxw3"]


[storage]
type = "Redis"
connection_params = "redis://127.0.0.1:6379"

[chain]
type = "PreProd"

[intersect]
type = "Point"
value = [
    8261225,
    "103ff3cfec6e388db803fc10dbdecb3026b4a51382008d01ff3f9121be6fa6e4",
]
