# get data from remote relay node
[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"

# get data from local node
# [source]
# type = "N2C"
# path = "data/cardano-node-mainnet/node.socket"

[enrich]
type = "Sled"
db_path = "data/scrolls/sled_db"

[[reducers]]
type = "UtxoByAddress"
key_prefix = "c1"
# filter = ["addr1qxkwuk0fsg425h8tkfyurhj85gj0h9wy8trflh5dcey73cp5ngu35tg3rr3v0nh7gvtucgjvguwrkc3ef6p4wvsdpsssl5uzp4"] # smolStaking fulladdr (see below)

# [[reducers]]
# type = "TxCountByAddress"

# [[reducers]]
# type = "TxByHash"
# filter = ["addr1qxkwuk0fsg425h8tkfyurhj85gj0h9wy8trflh5dcey73cp5ngu35tg3rr3v0nh7gvtucgjvguwrkc3ef6p4wvsdpsssl5uzp4"]


[[reducers]]
type = "TxCountByAddress"
key_prefix = "tcba"
filter = { any_of = [
        { output_address = { exact = "addr1q8fukvydr8m5y3gztte3d4tnw0v5myvshusmu45phf20h395kqnygcykgjy42m29tksmwnd0js0z8p3swm5ntryhfu8sg7835c" }}
        # {
        #     "input_address": {
        #         "exact": "addr1q8fukvydr8m5y3gztte3d4tnw0v5myvshusmu45phf20h395kqnygcykgjy42m29tksmwnd0js0z8p3swm5ntryhfu8sg7835c"
        #     }
        # }
    ]}


[storage]
type = "Redis"
connection_params = "redis://127.0.0.1:6379"

[intersect]
type = "Point"
value = [70724778, "ff1b93cdfd997d4ea93e7d930908aa5905d788fe9efb4f95a8e01856d2872e18"]

[chain]
type = "Mainnet"

[policy]
missing_data = "Skip"