/**
 * carp
 * API for the Postgres database generated by Carp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TxAndBlockInfo } from './TxAndBlockInfo';
import { HttpFile } from '../http/http';

export class TransactionHistoryResponse {
    'transactions': Array<TxAndBlockInfo>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<TxAndBlockInfo>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionHistoryResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

