/**
 * carp
 * API for the Postgres database generated by Carp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address';
import { HttpFile } from '../http/http';

export class TransactionHistoryRequestAllOf {
    /**
    * Defaults to `ADDRESS_LIMIT.RESPONSE`
    */
    'limit'?: number;
    /**
    * Filter which uses of the address are considered relevant for the query.  This is a bitmask, so you can combine multiple options ex: `RelationFilterType.Input & RelationFilterType.Output`  Note: relations only apply to credentials and not to full bech32 addresses
    */
    'relationFilter'?: number;
    'addresses': Array<Address>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": "double"
        },
        {
            "name": "relationFilter",
            "baseName": "relationFilter",
            "type": "number",
            "format": "double"
        },
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<Address>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionHistoryRequestAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

